server:
  servlet:
    context-path: /product-price-inquiry/v1

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

api:
  info:
    title: Inditex technical test - Product price inquiry application
    description: This API contains services for inditex technical test driven by a trademark inquiry application
    version: 1.0.0
    license: Apache License Version 2.0
    licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
    groupName: inditex-technical-test
    apiVersion: /v1
  server:
    serviceUrl: http://localhost:8080
    pathMapping: /product-price-inquiry
  service:
    applicationName: product-price-inquiry-app
