DROP TABLE IF EXISTS BRANDS;

CREATE TABLE BRANDS (
  BRAND_ID INT NOT NULL PRIMARY KEY,
  BRAND_DESC VARCHAR(25) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR(10) NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR(10) NOT NULL
);

INSERT INTO BRANDS
   (BRAND_ID, BRAND_DESC, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
 VALUES
   (1, 'ZARA', CURRENT_TIMESTAMP, 'TEST', CURRENT_TIMESTAMP, 'TEST');

DROP TABLE IF EXISTS PRICES;

CREATE TABLE PRICES (
  INTERNAL_ID INT AUTO_INCREMENT  PRIMARY KEY,
  BRAND_ID INT NOT NULL,
  START_DATE TIMESTAMP NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  PRICE_LIST INT NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY INT NOT NULL,
  PRICE DOUBLE NOT NULL,
  CURR VARCHAR(3) NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL,
  CREATED_BY VARCHAR(10) NOT NULL,
  UPDATED_AT TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR(10) NOT NULL,
  FOREIGN KEY (BRAND_ID) REFERENCES BRANDS (BRAND_ID)
 );

 INSERT INTO PRICES
   (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR, CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY)
 VALUES
   (1, PARSEDATETIME('2020-06-14-00.00.00', 'yyyy-MM-dd-HH.mm.ss'), PARSEDATETIME('2020-12-31-23.59.59', 'yyyy-MM-dd-HH.mm.ss'), 1, 35455, 0, 35.50, 'EUR', CURRENT_TIMESTAMP, 'TEST', CURRENT_TIMESTAMP, 'TEST'),
   (1, PARSEDATETIME('2020-06-14-15.00.00', 'yyyy-MM-dd-HH.mm.ss'), PARSEDATETIME('2020-06-14-18.30.00', 'yyyy-MM-dd-HH.mm.ss'), 1, 35455, 1, 25.45, 'EUR', CURRENT_TIMESTAMP, 'TEST', CURRENT_TIMESTAMP, 'TEST'),
   (1, PARSEDATETIME('2020-06-15-00.00.00', 'yyyy-MM-dd-HH.mm.ss'), PARSEDATETIME('2020-06-15-11.00.00', 'yyyy-MM-dd-HH.mm.ss'), 1, 35455, 1, 30.50, 'EUR', CURRENT_TIMESTAMP, 'TEST', CURRENT_TIMESTAMP, 'TEST'),
   (1, PARSEDATETIME('2020-06-15-16.00.00', 'yyyy-MM-dd-HH.mm.ss'), PARSEDATETIME('2020-12-31-23.59.59', 'yyyy-MM-dd-HH.mm.ss'), 1, 35455, 1, 38.95, 'EUR', CURRENT_TIMESTAMP, 'TEST', CURRENT_TIMESTAMP, 'TEST');
